portfolab5/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('portfolio.urls')),
    path('', include('users.urls')),
]

portfolio/urls.py
from django.shortcuts import render
from django.urls import path
from . import views

app_name = "portfolio"

urlpatterns = [
    path('index', views.index_page_view, name='index'),
    path('index2', views.index2_page_view, name='index2'),
    path('index3', views.index3_page_view, name='index3'),
    path('home', views.home_page_view, name='home'),
    path('new/', views.new_post_view, name='new'),
    path('edit/<int:post_id>', views.edit_post_view, name='edit'),
    path('delete/<int:post_id>', views.delete_post_view, name='delete'),
    path('like/<int:post_id>/', views.like_post, name='like_post'),
]

users/urls.py
from . import views
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', views.index, name='index'),
    path('login', views.login_view, name='login'),
    path('logout', views.logout_view, name='logout'),
]

portfolio/models.py
from django.db import models

# Create your models here.
class Post(models.Model):
    autor = models.CharField(max_length=200)
    data = models.DateTimeField(auto_now_add=True)
    titulo = models.CharField(max_length=200)
    descricao = models.CharField(max_length=500)
    link = models.URLField(blank=True, null=True)
    likes = models.PositiveIntegerField(default=0)

    def __str__(self):
        return self.titulo

users/models.py
from django.db import models

# Create your models here.

portfolio/forms.py
from django import forms
from django.forms import ModelForm
from .models import Post

class PostForm(ModelForm):
    class Meta:
        model = Post
        fields = '__all__'

        labels = {
            'titulo': 'Título',
            'descricao': 'Descrição'
        }

portfolio/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import render, redirect
from django.urls import reverse
from .models import Post
from .forms import PostForm
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required

import datetime

# Create your views here.

def index_page_view(request):	
    return render(request, 'portfolio/index.html')

def index2_page_view(request):
	return render(request, 'portfolio/index2.html')

def index3_page_view(request):
	return render(request, 'portfolio/index3.html')

def home_page_view(request):
	context = {'posts': Post.objects.all()}
	return render(request, 'portfolio/home.html', context)

def new_post_view(request):
    form = PostForm(request.POST or None)
    if form.is_valid():
        form.save()
        return redirect('portfolio:home')
    context = {'form': form}
    return render(request, 'portfolio/new.html', context)

def edit_post_view(request, post_id):
    post = Post.objects.get(id=post_id)
    form = PostForm(request.POST or None, instance=post)

    if form.is_valid():
        form.save()
        return HttpResponseRedirect(reverse('portfolio:home'))

    context = {'form': form, 'portfolio_id': post_id}
    return render(request, 'portfolio/edit.html', context)


def delete_post_view(request, post_id):
    Post.objects.get(id=post_id).delete()
    return HttpResponseRedirect(reverse('portfolio:home'))

def like_post(request, post_id):
    post = Post.objects.get(id=post_id)
    post.likes += 1
    post.save()
    return redirect('portfolio:home')

posts/views.py
from django.shortcuts import render

# Create your views here.

users/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import render, redirect
from django.urls import reverse
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required

# Create your views here.
def index(request):	
	if not request.user.is_authenticated:
		return HttpResponseRedirect(reverse('login'))
	return render(request, "portfolio/index.html")

def login_view(request):
	if request.method == "POST":
		username = request.POST['username']
		password = request.POST['password']
		user = authenticate(request, username=username, password=password)
		if user is not None:
			login(request, user)
			return HttpResponseRedirect(reverse('portfolio:index'))
		else:
			return render(request, "users/login.html", {'message': "Invalid credentials."})

	return render(request, "users/login.html")

def logout_view(request):
	logout(request)
	return render(request, "users/login.html", {"message": "Logged out."})

portfolio/templates/portfolio/base.html
{% load static %}
<!DOCTYPE html>
<html lang="pt">

    <head>
        <link rel="preconnect" href="https://fonts.googleapis.com">
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
        <link href="https://fonts.googleapis.com/css2?family=Montserrat&display=swap" rel="stylesheet">
        <link href="{% static 'portfolio/css/style.css' %}" rel="stylesheet">
        <link href="https://cdn.jsdelivr.net/npm/remixicon@2.5.0/fonts/remixicon.css" rel="stylesheet">
        <meta charset="utf-8">
        <meta name="author" content="João Serralha">
        <meta name="viewport" content="width=device-width,initial-scale=1.0">
        <style>
                    * {
            box-sizing: border-box;
        }

        body {
            margin: 0;
            padding: 0;
            background-color: #f2f2f2;
        }
        
        .basecontainer {
            display: flex;
            flex-direction: column;
            min-height: 100vh;
        }
        
        header {
            background-color: #333;
            color: #fff;
            padding: 20px;
        }
        
        h1 {
            margin: 0;
            font-size: 28px;
        }
        
        p {
            margin: 10px 0 0;
            font-size: 16px;
        }
        
        main {
            flex: 1;
            padding: 20px;
        }
        </style>
    </head>
    <body>
        <div class="basecontainer">
            <header>
                <h1>Blog</h1>
                <p>App to manage posts inside a blog</p>
                <main>
                    {% block main %}

                    {% endblock %}
                </main>
            </header>
        </div>    
    </body>
</html>

portfolio/templates/portfolio/edit.html
{% extends 'portfolio/base.html' %}

{% block main %}
<h3>Blog</h3>
    <form action="{% url 'portfolio:edit' portfolio_id %}" method="POST">
        {% csrf_token %}
        {{ form.as_p }}

        <a href="{% url 'portfolio:home' %}" role="button" class="btn btn-warning">Cancel</a>
        <input type="submit" value="Gravar" class="btn btn-success" >
        <a href="{% url 'portfolio:delete' portfolio_id %}" role="button" class="btn btn-danger">Delete</a>
    </form>
{% endblock %}

portfolio/templates/portfolio/home.html
{% extends 'portfolio/base.html' %}

{% block main %}
    {% for post in posts %}
        <p> 
           {{ post.titulo }}
           <a href="{% url 'portfolio:like_post' post.id %}">Like</a>
           <a href="{% url 'portfolio:edit' post.id %}" class="btn btn-warning">Edit</a>
        </p>
   {% endfor %}
        <a href="{% url 'portfolio:new' %}" class="btn btn-success btn-block">+ New Post</a>
{% endblock %}

portfolio/templates/portfolio/index.html
{% load static %}
<!DOCTYPE html>
<html lang="pt">

    <head>
        <link rel="preconnect" href="https://fonts.googleapis.com">
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
        <link href="https://fonts.googleapis.com/css2?family=Montserrat&display=swap" rel="stylesheet">
        <link href="{% static 'portfolio/css/style.css' %}" rel="stylesheet">
        <link href="https://cdn.jsdelivr.net/npm/remixicon@2.5.0/fonts/remixicon.css" rel="stylesheet">
        <meta charset="utf-8">
        <meta name="author" content="João Serralha">
        <meta name="viewport" content="width=device-width,initial-scale=1.0">
        <body>
            <nav class="navegation">
              <div class="navegation-left">
                <img src="https://media.discordapp.net/attachments/1084203416294801419/1100796529247268934/1dc417f222594a82b0b24a6059eef40d_6.png" class="logo">
                <a href="index.html" class="linkSlogan">乛ＳＨＡＤＯＷ ×͜×</a>
              </div>
                <div class="navegation-right">
                  <input type="checkbox" id="switch" /><label id="label-togg" for="switch">Toggle</label>
                  <a href="index" class="link">Home</a>
                  <a href="index2" class="link">Projects</a>
                  <a href="index3" class="link">Web</a>
                  <a href="home" class="link">Blog</a>
                  <a href="{% url 'logout'%}" class="link">Log out</a>
                </div>
            </nav>
              <main class="allMenus">
                <div class="backgroundMenu">
                  João Serralha
                  <br>
                  <br>
                  Computer Engineering Student
                  <br>
                  <br>
                  <script>
            
                    const nome = prompt("What is your name?");
        
                    // imprimir o nome em diferentes sítios
                    console.log(`Hello, ${nome}!`);
                    alert(`Welcome, ${nome}!`);
                    document.write(`Hello ${nome}`);
        
                   </script>
                </div>
                <div id="test1">
                  <input type="text" id="expressioninsert">
                  <div id="legend"></div>
                  <button onclick="inserirLegenda()" id="insert-btn">Insert</button>
                </div>
                
                <div class="container">               
                  <p>
                    <article class="apresentation">
                      <script>
                        document.write(`Hello ${nome}`);
                      </script>
                      <h6>&#128075 About me</h6>
                      <p>
                        <ul class="motivations">
                          <li>
                            Took interest in programming when I was 12
                          </li>
                          <li>
                            Always passionate for learning new things
                          </li>
                        </ul>
                      </p>
                      <br>
                      <h6>&#128102 Personal Interests</h6>
                      <p>
                        <ul class="interests">
                          <li>
                            Spending time with friends
                          </li>
                          <li>
                            Watching series, films and Esports Games
                          </li>
                          <li>
                            Playing some games
                          </li>
                        </ul>
                      </p>
                      <br>
                      <h6>&#128203 Soft Skills</h6>
                      <p>
                        <ul class="skills">
                          <li>
                            Loyal and trustful
                          </li>
                          <li>
                            Focused and analytical
                          </li>
                          <li>
                            Motivated and responsible
                          </li>
                        </ul>
                      </p>
                    </article>
                  </p>             
                  <div class="box">
                      <div class="imgBox">
                        <img src="https://cdn.discordapp.com/attachments/1084203416294801419/1101953037091754034/diagrama.drawio-3.png">
                      </div>
                      <div class="author-container">
                        <p class="author-name">
                          Hi! It's me
                        </p>
                        <p class="author-role">
                          João Serralha
                          <br>
                          <script>
                              document.write(`Hello ${nome}`);
                          </script>
                        </p>
                      </div>
                      <!-- Prevents stuff from getting bad -->
                      <div></div>
                  </div>
                </div>
              
                <div id="test2">
                  <p>Introduce an arithemetic expression:</p>
                    <input type="text" id="expression">
                    <br><br>
                    <button id="calculate-btn">{ Calculate }</button>
                    <button id="clear-btn">{ Clear Result }</button>
                    <br><br>
                  <p id="result"></p>
                </div>
                <div class="footerPage">
                  <article class="footerInfo">
                    <h6>Let's get in touch &#128681</h6>
                    <p class="contactText">
                      Need anything built, want to work together or simply want to have a chat?
                    </p>
                  </article>
                    <br>
                  <div>
                    <a href="https://www.instagram.com/joaoserralha_/" class="icon icon--instagram">
                      <i class="ri-instagram-line"></i>
                    </a>
                    <a href="https://twitter.com/shedawzera" class="icon icon--twitter">
                      <i class="ri-twitter-line"></i>
                    </a>
                    <a href="https://www.linkedin.com/in/jo%C3%A3o-serralha-b078ab232/" class="icon icon--linkedin">
                      <i class="ri-linkedin-line"></i>
                    </a>
                    <a href="https://github.com/Shadow10Z" class="icon icon--github">
                      <i class="ri-github-line"></i>
                    </a>
                  </div>
                  <p id="footercopyrights">
                    João Serralha © 2023 Universidade Lusófona de Lisboa -
                  </p>
                </div>
              </main>
           <script>
              var myElement = document.getElementById('test1');
              myElement.onmouseover = function() {
                myElement.style.backgroundImage = "url('https://cdn.discordapp.com/attachments/1084203416294801419/1100805042245738658/image.png')";
              };
              myElement.onmouseout = function() {
                myElement.style.backgroundImage = "url('https://cdn.discordapp.com/attachments/1084203416294801419/1100757115506806915/image.png')";
              };
              
              var myElement2 = document.getElementById('test2');
              myElement2.onmouseover = function() {
                myElement2.style.backgroundImage = "url('https://cdn.discordapp.com/attachments/1084203416294801419/1100757115506806915/image.png')";
              };
              myElement2.onmouseout = function() {
                myElement2.style.backgroundImage = "url('https://cdn.discordapp.com/attachments/1084203416294801419/1100805042245738658/image.png')";
              };
           </script>
           <script>
            const toggleBtn = document.getElementById('label-togg');
            const content = document.querySelector('.footerPage');
            const content2 = document.querySelector('.backgroundMenu');
            const content3 = document.querySelector('.navegation');
            const content4 = document.querySelector('.container');

            toggleBtn.addEventListener('click', () => {
              content.classList.toggle('dark-mode');
              content2.classList.toggle('dark-mode');
              content3.classList.toggle('dark-mode');
              content4.classList.toggle('dark-mode');

              // Salva o modo atual no localStorage
              localStorage.setItem('dark-mode', content.classList.contains('dark-mode'));
              localStorage.setItem('dark-mode', content2.classList.contains('dark-mode'));
              localStorage.setItem('dark-mode', content3.classList.contains('dark-mode'));
              localStorage.setItem('dark-mode', content4.classList.contains('dark-mode'));
            });

            // Configura o modo inicial
            const isDarkMode = localStorage.getItem('dark-mode') === 'true';
            if (isDarkMode) {
              content.classList.add('dark-mode');
              content2.classList.add('dark-mode');
              content3.classList.add('dark-mode');
              content4.classList.add('dark-mode');
            }
           </script>
           <script>
            const data = new Date();
            const mes = data.toLocaleString('default', { month: 'long' });
            const dia = data.getDate();
            const ano = data.getFullYear();
            const dataFormatada = `${dia} de ${mes}, ${ano}`;
            const elementoData = document.getElementById('footercopyrights');
            elementoData.textContent += dataFormatada;
           </script>
           <script>
            function inserirLegenda() {
              let legenda = document.getElementById("expressioninsert").value;

              document.getElementById("legend").innerHTML = legenda;
            }
           </script>
           <script src="{% static 'portfolio/js/calculator.js' %}"></script>
        </body>
    </head>
</html>

portfolio/templates/portfolio/index2.html
{% load static %}
<!DOCTYPE html>
<html lang="pt">

    <head>
        <link rel="preconnect" href="https://fonts.googleapis.com">
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
        <link href="https://fonts.googleapis.com/css2?family=Montserrat&display=swap" rel="stylesheet">
        <link href="{% static 'portfolio/css/style.css' %}" rel="stylesheet">
        <meta charset="utf-8">
        <meta name="author" content="João Serralha">
        <meta name="viewport" content="width=device-width,initial-scale=1.0">
        <body>
            <nav class="navegation">
                <div class="navegation-left">
                    <img src="https://media.discordapp.net/attachments/1084203416294801419/1100796529247268934/1dc417f222594a82b0b24a6059eef40d_6.png" class="logo">
                    <a href="index.html" class="linkSlogan">乛ＳＨＡＤＯＷ ×͜×</a>
                </div>
                <div class="navegation-right">
                    <input type="checkbox" id="switch" /><label id="label-togg" for="switch">Toggle</label>
                    <a href="index" class="link">Home</a>
                    <a href="index2" class="link">Projects</a>
                    <a href="index3" class="link">Web</a>
                </div>
            </nav>
            <main class="allMenus">
              <div class="backgroundMenu">
                &#128588 Projects &#128588
                <br>
                <br>
                What I have done
              </div>
              <div class="test3">
                  <button class="btminesweeper" onclick="window.location.href = 'https://github.com/Shadow10Z/Minesweeper';">
                    Minesweeper
                    <span class="first"></span>
                    <span class="second"></span>
                    <span class="third"></span>
                    <span class="fourth"></span>
                  </button>
              </div>
              
              <div class="test8">       
                <article class="infominesweeper">        
                    <p>
                        The objective is to implement a game where the player controls a character to go from point A to point B in a minefield.

                        In Minesweeper, the player has to discover all the mines in a given terrain. The objective is to “clear” the land of mines, marking their location.
                    </p>             
                </article>
              </div>
            
              <div class="test4">
                 <button class="btdeisijungle" onclick="window.location.href = 'https://github.com/antonio-antunes-a22202276/LP2-22202276-22202133';">
                    DEISIJungle
                    <span class="first"></span>
                    <span class="second"></span>
                    <span class="third"></span>
                    <span class="fourth"></span>
                  </button>
              </div>

              <div class="test5">
                <article class="infodeisijungle">
                    <p>
                        One day, in a savannah very (very) far from here, the animals decided to find out who would be the best athlete amongst them. To do so, they defined a set of sporting events that they would compete against each other - whoever won the most events would be considered the King of the Jungle. The news quickly reached Tarzan, who did not want to stop participating in the competitions, convinced that he would easily win.
                    </p>
                </article>
              </div>

              <div class="test6">
                <button class="btdeisiflix" onclick="window.location.href = 'https://github.com/Shadow10Z/Deisiflix';">
                    DEISIFLIX
                    <span class="first"></span>
                    <span class="second"></span>
                    <span class="third"></span>
                    <span class="fourth"></span>
                  </button>
              </div>

              <div class="test7">
                <article class="infodeisiflix">
                    <p>
                        This project aims to develop an application in Java, that is capable of receiving and responding to requests for statistics on a movie database.
                    </p>
                </article>
              </div>
            </main>
            <script src="{% static 'portfolio/js/darkmode.js' %}"></script>      
        </body>
    </head>
</html>

portfolio/templates/portfolio/index3.html
{% load static %}
<!DOCTYPE html>
<html lang="pt">

    <head>
        <link rel="preconnect" href="https://fonts.googleapis.com">
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
        <link href="https://fonts.googleapis.com/css2?family=Montserrat&display=swap" rel="stylesheet">
        <link href="{% static 'portfolio/css/style.css' %}" rel="stylesheet">
        <meta charset="utf-8">
        <meta name="author" content="João Serralha">
        <meta name="viewport" content="width=device-width,initial-scale=1.0">
        <body>
            <nav class="navegation">
                <div class="navegation-left">
                    <img src="https://media.discordapp.net/attachments/1084203416294801419/1100796529247268934/1dc417f222594a82b0b24a6059eef40d_6.png" class="logo">
                    <a href="index.html" class="linkSlogan">乛ＳＨＡＤＯＷ ×͜×</a>
                </div>
                <div class="navegation-right">
                    <input type="checkbox" id="switch" /><label id="label-togg" for="switch">Toggle</label>
                    <a href="index" class="link">Home</a>
                    <a href="index2" class="link">Projects</a>
                    <a href="index3" class="link">Web</a>
                </div>
            </nav>
            <main class="allMenus">
              <div class="backgroundMenu">
                &#128187 Web &#128187
                <br>
                <br>
                What was used in this website
              </div>
              <div class="test9">
                  <button class="btminesweeper" onclick="window.location.href = 'https://html.com/';">
                    HTML
                    <span class="first"></span>
                    <span class="second"></span>
                    <span class="third"></span>
                    <span class="fourth"></span>
                  </button>
              </div>
              
              <div class="test8">       
                <article class="infominesweeper">        
                    <p>
                        <h3>HTML</h3> HypterText Markup Language
                        <br>
                        <br>
                        It's the standard markup language for Web pages. With HTML you can create your own Website
                    </p>             
                </article>
              </div>
            
              <div class="test10">
                 <button class="btdeisijungle" onclick="window.location.href = 'https://www.w3.org/Style/CSS/Overview.en.html';">
                    CSS
                    <span class="first"></span>
                    <span class="second"></span>
                    <span class="third"></span>
                    <span class="fourth"></span>
                  </button>
              </div>

              <div class="test5">
                <article class="infodeisijungle">
                    <p>
                      <h3>CSS</h3> Cascading Style Sheets
                      <br>
                      <br>
                      Cascading Style Sheets is a mechanism for adding styles to a web page, either applied directly to HTML tags or contained within style tags
                    </p>
                </article>
              </div>

              <div class="test11">
                <button class="btdeisiflix" onclick="window.location.href = 'https://www.javascript.com/';">
                   JS
                    <span class="first"></span>
                    <span class="second"></span>
                    <span class="third"></span>
                    <span class="fourth"></span>
                  </button>
              </div>

              <div class="test7">
                <article class="infodeisiflix">
                    <p>
                      <h3>JS</h3> JavaScript
                      <br>
                      <br>
                      Along with HTML and CSS , JavaScript is one of the three main technologies of the World Wide Web. JavaScript enables interactive web pages and is therefore an essential part of web applications. The vast majority of websites do, and all major browsers have a dedicated JavaScript engine to run it.
                    </p>
                </article>
              </div>
            </main>
            <script src="{% static 'portfolio/js/darkmode.js' %}"></script>      
        </body>
    </head>
</html>

portfolio/templates/portfolio/new.html
{% extends 'portfolio/base.html' %}

{% block main %}
<h3>Novo Post</h3>
    <form action="" method="POST">
        {% csrf_token %}
        {{ form.as_p }}

        <a href="{% url 'portfolio:home' %}" role="button" class="expression">Cancel</a>
        <input type="submit" value="Gravar" class="btn btn-success" >
    </form>
{% endblock %}

users/templates/users/login.html
{% extends 'portfolio/base.html'%}

{% block main %}
    <form action="{% url 'login' %}" method="post">
        {% csrf_token %}
        <input type="text" name="username" placeholder="Username">
        <input type="password" name="password" placeholder="Password">
        <input type="submit">
    </form>
{% endblock %}